### ISSUE TITLE
Opção de Shuffle

### ISSUE THREAD

**Issue by GustavoWinter** [hmaranhao/giphy-app#1]
Olá, faço parte do time da 87 e gostaria de parabeniza-lo pela entrega do teste.

Também, gostaria de perguntar, pois notei que você não adicionou a opção de shuffle, o que te levou a deixar a mesma de fora.

Abs

**Comment by hmaranhao** [comment]
Olá Gustavo, agradeço.
Em meu desenvolvimento e na forma com que construí o app decidi que a opção "Shuffle" perdeu um pouco o sentido pois eu já mostro 16 gifs baseado na busca do usuário, e essa opção é bem utilizada quando o retorno é apenas um, como no caso do slack onde pesquisamos e temos essa opção pra achar o gif que mais se enquadra no que queremos expressar.
Acredito ter seguido uma linha diferente até do que o teste propôs, mas optei por fazer assim porque é um recurso legal pro portifólio e até mesmo pra usar no meu dia-a-dia, claro que ainda podendo melhorar muito.
